// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtO1V9Qtu3ASpMhJts2WbcpAl3Rr4i4Tw',
    appId: '1:738192834266:web:2da16c4503ee52c477afe3',
    messagingSenderId: '738192834266',
    projectId: 'wheel-it-78ea9',
    authDomain: 'wheel-it-78ea9.firebaseapp.com',
    databaseURL: 'https://wheel-it-78ea9-default-rtdb.firebaseio.com',
    storageBucket: 'wheel-it-78ea9.appspot.com',
    measurementId: 'G-6SRXJKCR06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYUidlmHTJO_PoFYvU3KVAR1Ho1JMNf1g',
    appId: '1:738192834266:android:bd76871ea231726777afe3',
    messagingSenderId: '738192834266',
    projectId: 'wheel-it-78ea9',
    databaseURL: 'https://wheel-it-78ea9-default-rtdb.firebaseio.com',
    storageBucket: 'wheel-it-78ea9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0t9rAy7IMDAq6OY5vsBAokp3XZGUO1I',
    appId: '1:738192834266:ios:ed3f7bef5839db0577afe3',
    messagingSenderId: '738192834266',
    projectId: 'wheel-it-78ea9',
    databaseURL: 'https://wheel-it-78ea9-default-rtdb.firebaseio.com',
    storageBucket: 'wheel-it-78ea9.appspot.com',
    iosClientId: '738192834266-9nckmfud0fnrb1phfpabur2ur6h0jivb.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0t9rAy7IMDAq6OY5vsBAokp3XZGUO1I',
    appId: '1:738192834266:ios:ed3f7bef5839db0577afe3',
    messagingSenderId: '738192834266',
    projectId: 'wheel-it-78ea9',
    databaseURL: 'https://wheel-it-78ea9-default-rtdb.firebaseio.com',
    storageBucket: 'wheel-it-78ea9.appspot.com',
    iosClientId: '738192834266-9nckmfud0fnrb1phfpabur2ur6h0jivb.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtO1V9Qtu3ASpMhJts2WbcpAl3Rr4i4Tw',
    appId: '1:738192834266:web:e71847bdd6380fc577afe3',
    messagingSenderId: '738192834266',
    projectId: 'wheel-it-78ea9',
    authDomain: 'wheel-it-78ea9.firebaseapp.com',
    databaseURL: 'https://wheel-it-78ea9-default-rtdb.firebaseio.com',
    storageBucket: 'wheel-it-78ea9.appspot.com',
    measurementId: 'G-D23L4L72VW',
  );
}
